name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Print a greeting
        run: sudo apt-get install nodejs
      - name: Print a greeting
        run: sudo gem install execjs
      - name: Print a greeting
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh |sudo  bash 
      - name: nvm install 5
        run: sudo nvm install 5.9.1
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}

